### ISSUE TITLE
Failed training

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/mpt_faces#11]
I do now know why, but I get this error when trying to run this code: 
python main.py train
This is the error I get:
![Screenshot 2024-05-13 225608](https://github.com/lucasthierry17/mpt_faces/assets/112621937/12660473-4ea7-4fb2-b24b-b71e2bc5d5d7)

Anyone know why?

**Comment by NielsWulf** [comment]
@lucasthierry17 The issue lays within the old Images, just delete them an take new ones.

**Comment by lucasthierry17** [comment]
@NielsWulf worked! Thx
