### ISSUE TITLE
Recognize the person in front of the camera

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/mpt_faces#3]
Requirements: we need the png and csv files. 
If a person (which already has a folder with the files) steps in front of the camera, the program should recognize the person. 
There should be a blue square around the face and the name should appear on top of the square.

**Comment by lucasthierry17** [comment]
Test it out with the command: 
python main.py live --border 0.2
Remember to run the record and training before!

**Comment by NielsWulf** [comment]
This is works now
