### ISSUE TITLE
Save PNG every x frames

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/mpt_faces#4]
If the camera is opened, we want to save the png and csv files in a existing folder (if the person was already in front of the camer) or a new folder (if no folder exists). The csv file should contain the coordinates of the head of the person and the png file should contain the picture of the blue square plus an extra border

**Comment by lucasthierry17** [comment]
I added the file png_test.py to the repo. It saves a png and csv file in the objects folder. Please test it and let me know if you encounter any issues

**Comment by NielsWulf** [comment]
@lucasthierry17 functions without any issues.
